#%RAML 1.0 SecurityScheme
type: x-facebook
description:
  Used to send the facebook access token using the Oauth2 Bearer token
describedBy:
  headers:
    Authorization:
      description:
        Do not use with the "acces_token" query string or body param
      example: Bearer CAAIjRkSocuoBAI2nsD9aIRrGX7aOiNByXjJTbmlKi011wldd4IsjtVwYWQ84Fak55qOzmX2UhDwJoHznNs3Ck0cLTMZAqaheagVAQUsm9q07DZCO7ZAPXmJ6H6nGA6ryZAAZC8ZAA7Q0Hu4YEuqEeQ9Ou20DzQYi5yvKvpDwIc3utAsN35IdRZAcMdhSjuTGFyUlZChin5l4yi7o2HJmGZB3celXb2F40mDg3wSoFHHHHHHHHH
  queryParameters:
    acces_token:
      description:
        Do not use with the "acces_token" body param or "Authorization" header
      example: CAAIjRkSocuoBAI2nsD9aIRrGX7aOiNByXjJTbmlKi011wldd4IsjtVwYWQ84Fak55qOzmX2UhDwJoHznNs3Ck0cLTMZAqaheagVAQUsm9q07DZCO7ZAPXmJ6H6nGA6ryZAAZC8ZAA7Q0Hu4YEuqEeQ9Ou20DzQYi5yvKvpDwIc3utAsN35IdRZAcMdhSjuTGFyUlZChin5l4yi7o2HJmGZB3celXb2F40mDg3wSoFHHHHHHHHH
  responses:
    401:
      description:
        The facebook access token is invalid
