#%RAML 1.0 DataType

type: object
properties:
  signature:
    type: string
    description:
      The signature in sha1 format
  uri:
    type: string
    description:
      the upload uri
  id:
    type: string
    description:
      the public id of the image
  time:
    type: string
    description:
      the timestampt for the upload
