#%RAML 1.0
title: Sparkd

version: v1

baseUri: http://persona-mono.herokuapp.com/{version}

mediaType:
  - application/json

protocols:
  - HTTP

traits:
  sendError: !include traits/error.raml

securitySchemes:
  facebook: !include securitySchemes/facebook.raml
  bearer: !include securitySchemes/bearer.raml

types:
  Auth: !include types/auth.raml
  User: !include types/user.raml
  Sparkd: !include types/sparkd.raml
  Like: !include types/like.raml
  Language: !include types/language.raml

securedBy: [bearer]

/auth:
  is: [sendError]
  securedBy: [facebook]
  post:
    responses:
      200:
        body: Auth

/users:
  is: [sendError]
  get:
    responses:
      200:
        body: User[]
  post:
    responses:
      201:
        body: User
  /me:
    get:
      responses:
        200:
          body: User
    patch:
      responses:
        200:
          body: User
    /sparkds:
      get:
        responses:
          200:
            body: Sparkd[]
      /{sparkdId}:
        get:
          responses:
            200:
              body: Sparkd
        patch:
          responses:
            200:
              body: Sparkd

  /{userId}:
    get:
      responses:
        200:
          body: User
    delete:
      responses:
        204:

/likes:
  is: [sendError]
  post:
    responses:
      201:
        body: Like

/sparkds:
  is: [sendError]
  get:
    responses:
      200:
        body: Sparkd[]

/languages:
  is: [sendError]
  securedBy: null
  get:
    responses:
      200:
        body: Language[]

/cloudinary-signatures:
  is[sendError]
  securedBy: null
  get:
    response:
      200:
        body: Signature
